### ISSUE TITLE
Exporting Nine-Patch does nothing

### ISSUE THREAD

**Issue by kuswanto** [Ashung/Android_Res_Export#10]
Just tried out your plugin, it's give hopes for Android UI designer :)
However the Nine-Patch export is not working. I tested it on Sketch 46.2

**Comment by Ashung** [comment]
@kuswanto try to update version 2.3.0

**Comment by kuswanto** [comment]
Lovely, thank you for the update, but now the menu is in Chinese. 
![screen shot 2017-10-11 at 11 23 58](https://user-images.githubusercontent.com/1097842/31422266-c1462902-ae76-11e7-9c44-cb17fca03641.png)

**Comment by Ashung** [comment]
Sorry, I commit the Chinese file. run "帮助“ - ”更改菜单语言“

**Comment by Ashung** [comment]
@kuswanto If you use macOS high Sierra, you must update Android Res Export 2.3.3.
