### ISSUE TITLE
Trying to export Nine-Patches

### ISSUE THREAD

**Issue by rodi01** [Ashung/Android_Res_Export#11]
HI,

I'm trying to export the nine-patches and I'm getting this on the console: "launch path not accessible".

Nothing happens. Running 2.3.1 version. 

Thanks

**Comment by Ashung** [comment]
@rodi01 Can you run follow script in Sketch, and show me the out put.

```
@import "~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Android_Res_Export.sketchplugin/Contents/Sketch/lib/common.js"

runCommand("/bin/bash", ["-l", "-c", "which convert"], function(status, msg) {
    log(status)
    log(msg)
});

log(NSProcessInfo.processInfo().environment().objectForKey("SHELL"))
log(NSProcessInfo.processInfo().operatingSystemVersionString())
```

**Comment by rodi01** [comment]
![](https://d26dzxoao6i3hh.cloudfront.net/items/291x0M262A090Z2p3G2k/Screen%20Shot%202017-11-07%20at%209.00.14%20PM.png?v=0870a909)

**Comment by rodi01** [comment]
I'm using ZSH for my shell. 

Here is the result:

/bin/zsh
/usr/bin:/bin:/usr/sbin:/sbin
Version 10.13.1 (Build 17B48)

Script executed in 0.019243s

**Comment by Ashung** [comment]
@rodi01 update to Android Res Export 2.3.2, i fixed this bug.

**Comment by Ashung** [comment]
@rodi01 update to Android Res Export 2.3.3, sorry the version 2.3.2 have a big bug.

**Comment by rodi01** [comment]
Perfect, thanks!
