### ISSUE TITLE
After updating: Export vector drawables: Always get a "You can't export assets to this folder"

### ISSUE THREAD

**Issue by pdlipman-apx** [Ashung/Android_Res_Export#12]
After updating to latest, whenever i try and export an existing vector drawable (that exported fine before), i get a warning that says `You can't export assets to this folder`. 

I tried changing the export folder to a variety of locations incase something was blocking them, but nothing is working.

**Comment by Ashung** [comment]
@pdlipman-apx update the new version 2.3.3

**Comment by pdlipman-apx** [comment]
Working. thank you!

**Comment by smoothdvd** [comment]
This issue appears in 2.6.3 + Sketch 48.2 again.
