### ISSUE TITLE
No any vector drawable asset. Even for the vector not bitmap.

### ISSUE THREAD

**Issue by Pei116** [Ashung/Android_Res_Export#13]
I just tried to export vector drawables but it always says "No any vector drawable asset." even when i try to export the vector not bitmap.
![screenshot](https://user-images.githubusercontent.com/2336333/33355884-6a6dcdf2-d4f4-11e7-87b6-49254fc5de5b.png)

**Comment by Ashung** [comment]
Select the icon first, then run "New Vector Drawable Asset" from plugin menu.
You must create vector drawable assets before export.

**Comment by Pei116** [comment]
Sure, that's what I'm doing with this one.
[Footer.zip](https://github.com/Ashung/Android_Res_Export/files/1512565/Footer.zip)

**Comment by Ashung** [comment]
Select the icon  then run "New Vector Drawable Asset" to create a vector drawable first.

**Comment by Pei116** [comment]
Wow, works like a charm after doing that!
