### ISSUE TITLE
Error: You need to update svg2vectordrawable

### ISSUE THREAD

**Issue by xodo-shared** [Ashung/Android_Res_Export#15]
Hi, I installed this plugin today via SketchRunner, and I installed svgo (version 1.0.3) and svg2vectordrawable (version 1.1.9) globally with npm. I used `New Vector Drawable Assets` a few times, then I tried `Export Vector Drawables`. It fails with the error "You need to update svg2vectordrawable", even though I have the latest version. Any idea what's going on?

**Comment by Ashung** [comment]
What's your macOS version, it works in 10.12.3 and 10.13.2.

**Comment by mrPsycho** [comment]
hello, i have same issue
![screen shot 2018-01-31 at 18 16 23](https://user-images.githubusercontent.com/883964/35631978-69b8cc38-06b6-11e8-9c4c-da34f4264ab1.png)

mac os 10.13.3

tried to install `npm` with downloaded `pkg` and with `brew`

**Comment by Ashung** [comment]
@xodo-shared @mrPsycho update plugin to v2.3.12.

**Comment by mrPsycho** [comment]
works, thanks a lot!

**Comment by kty** [comment]
Still doesn't work and getting the alert. Plugin 2.3.12, macOS 10.13.3, svg2vectordrawable 1.1.10.

**Comment by pdlipman-apx** [comment]
Running into this bug again as of latest pull on macOS 10.13.6

**Comment by Ashung** [comment]
@pdlipman-apx not a bug, I updated svg2vectordrawable, now support export vector with gradients. 

Android Res Export 3.x must install svg2vectordrawable 2.x.
