### ISSUE TITLE
新建位图资源时只创建一个空的组，没有切片图层。

### ISSUE THREAD

**Issue by EggKim** [Ashung/Android_Res_Export#19]
![1536492101963](https://user-images.githubusercontent.com/39717399/45263931-a6ec4a00-b465-11e8-93d7-e650eb2d2a41.jpg)
![1536492097063](https://user-images.githubusercontent.com/39717399/45263932-b1a6df00-b465-11e8-9b68-1c3891ae56e4.jpg)

**Comment by Ashung** [comment]
已修复. V3.2.0
