### ISSUE TITLE
Export Nine-Patch Assets is not working properly

### ISSUE THREAD

**Issue by dperhaj** [Ashung/Android_Res_Export#20]
Nine-patch export was working good until v3. I'm using latest Sketch (51.3 now).

Now it creates half-pixels on that solid black 1px lines for patches that should be solid. 
See the example screenshot, zoom in on the top patch.
https://imgur.com/a/OVyfms3

On the older version it was fine (v2.3).

Also, I noticed that under High Sierra, plug-in has problem with exporting to newly created folders (I presume it's due to writing permissions). I go round this problem by exporting to existing folder  (Desktop for example).

**Comment by Ashung** [comment]
I use Android Res Export 3.4.0, Sketch 51.3 on macOS High Sierra 10.13.5, and all works fine. Can you send me the sketch file.

**Comment by dperhaj** [comment]
I tried again using newest plugin version, and got the same result. Also, my coworkers on other Macs are getting the same (similiar configurations).

[test.zip](https://github.com/Ashung/Android_Res_Export/files/2427523/test.zip)

What I noticed that maybe the PNG exporting "engine" is changed from v2 to v3? Cause I use Image optimizer as a standalone plugin that gets activated after I export something through Sketch native export option, and in case of using v2 of plugin the ImgOptim gets activated, while on v3 it's bypased.

**Comment by thebytegrill** [comment]
![screenshot 2018-11-23 at 3 15 51 pm](https://user-images.githubusercontent.com/754407/48936994-b5a9af80-ef32-11e8-963c-6172ef3ee51e.png)
Can confirm this is an issue with the 3.7.0 plugin version and Sketch 52.4
The black lines are grey at the extremities. 
Thanks, your plugin has really helped me a lot so far.

**Comment by Ashung** [comment]
@thebytegrill what's your macOS version?

**Comment by dperhaj** [comment]
I'm still using v2.3 for 9patch export. Some of the other functionalities are broken, but for 9patches it does the job. 

@Ashung have you been able to identify what's causing the problem in the new version?

To be honest, I haven't found any good 9patch exporter plugin, yours works the best. Thank you for your work so far!

**Comment by Ashung** [comment]
It only appears in mac with retina display, I think it is fixed, update v3.8.0

**Comment by dperhaj** [comment]
It's working now!
It's a life saver, thank you!
