### ISSUE TITLE
Exported Vector Drawables appear to maintain offset internal to transform in artboard

### ISSUE THREAD

**Issue by pdlipman-apx** [Ashung/Android_Res_Export#21]
Android Res 3.6.0 in Sketch 52.2

*Observed*
- Recently started noticing that when i export a vector drawable and open it in Android Studio, the icon wont be visible in the icon preview because it appears very offset from 0,0 position.  
- If I take my icon and place its transform at 0,0 in my artboard prior to exporting the vector drawable, then it will appear normally in android studio.  

Did something change? When bulk exporting lots of assets, its more convenient to leave the drawables arranged in a grid in the Sketch artboard, rather then crushed on top of each other at 0,0.  Is it possible to have the plugin do this operation during export? Did it used to do this? Am I missing an update somwhere?

**Comment by Ashung** [comment]
Fixed it, update 3.7.0.
