### ISSUE TITLE
Unable to export vectors even after updating svg2vectordrawable

### ISSUE THREAD

**Issue by jaysondc** [Ashung/Android_Res_Export#22]
Upon trying to export a Vector Asset, I get this pop up even though I've already run the command to install svg2vectordrawable.

![image](https://user-images.githubusercontent.com/10622411/52158995-64651d00-2653-11e9-8b8c-618383193984.png)

I've reinstalled and updated node (11.9.0), svg2vectordrawable (2.6.5), and android_res_export (3.8.0) and even resorted to restarting my computer with no avail. MacOS 10.12.6

Here's the log from the install.
```
➜  ~ sudo npm install -g svg2vectordrawable
/usr/local/bin/s2v -> /usr/local/lib/node_modules/svg2vectordrawable/bin/svg2vectordrawable
/usr/local/bin/svg2android -> /usr/local/lib/node_modules/svg2vectordrawable/bin/svg2vectordrawable
/usr/local/bin/svg2avd -> /usr/local/lib/node_modules/svg2vectordrawable/bin/svg2vectordrawable
/usr/local/bin/svg2drawable -> /usr/local/lib/node_modules/svg2vectordrawable/bin/svg2vectordrawable
/usr/local/bin/svg2vector -> /usr/local/lib/node_modules/svg2vectordrawable/bin/svg2vectordrawable
/usr/local/bin/svg2vectordrawable -> /usr/local/lib/node_modules/svg2vectordrawable/bin/svg2vectordrawable
+ svg2vectordrawable@2.6.5
added 58 packages from 89 contributors in 3.105s
```

**Comment by Ashung** [comment]
Open the Terminal and type `s2v`, if show some error message, you need uninstall use `sudo npm uninstall -g svg2vectordrawable` and reinstall use `sudo npm install -g svg2vectordrawable`.

**Comment by jaysondc** [comment]
@Ashung I figured it out! There was a typo in my bash_profile stopping it from running. Thanks!
