### ISSUE TITLE
app icon export problem

### ISSUE THREAD

**Issue by klipovszky** [Ashung/Android_Res_Export#24]
my problem, if I export my adaptive app icon, all files in all folder got a dimension 192px x 192px in the xxxhdpi or mhdpi so the result is a blurry image on the phones.

![mipmap-mdpi_and_mipmap-xxxhdpi_and_sketch-export-assets-master](https://user-images.githubusercontent.com/15214130/64182716-f2fb8000-ce68-11e9-9f47-ce7f1f28b572.jpg)

**Comment by Ashung** [comment]
Fixed
