### ISSUE TITLE
导出点九切图不正常

### ISSUE THREAD

**Issue by Banlanhei** [Ashung/Android_Res_Export#25]
Sketch 59版本制作点九切图后，执行导出点九切图左下未正常生成黑线

**Comment by Ashung** [comment]
我自己验证了不会出现您反馈的问题，请尽量更详细的说明，配图或源文件。

**Comment by Banlanhei** [comment]
![点九切图导出左下没有黑线](https://user-images.githubusercontent.com/50607436/67147902-dbb70b80-f2cb-11e9-8d5f-cbd23c48cb1f.png)

**Comment by Banlanhei** [comment]
![点九切图导出左下没有黑线](https://user-images.githubusercontent.com/50607436/67147957-76afe580-f2cc-11e9-9f4f-a2ff5665a123.png)

**Comment by Banlanhei** [comment]
![点九切图导出左下没有黑线](https://user-images.githubusercontent.com/50607436/67148129-48cba080-f2ce-11e9-86b1-d8480caff4d3.png)
