### ISSUE TITLE
sketch 72.4 can't work

### ISSUE THREAD

**Issue by l5ee** [Ashung/Android_Res_Export#27]
help, sketch 72.4 can't work

**Comment by falkorichter** [comment]
we @sensorberg encountered the same problem :(

**Comment by robtoyo** [comment]
It is not just the newer sketch version. If you downgrade to an older Sketch version e.g. 71 but use a newer version of svg2vectordrawable e.g. 2.7.1 it will also break.

**Comment by falkorichter** [comment]
I created a test release @l5ee at https://github.com/sensorberg/Android_Res_Export/releases/tag/3.8.8-SNAPSHOT which you could try to use. It seems to work for me

**Comment by Ashung** [comment]
Download the new version. V4.0
