### ISSUE TITLE
Export Vector Drawables not working

### ISSUE THREAD

**Issue by tembloroso** [Ashung/Android_Res_Export#5]
Wanted to convert a PNG image to Vector Drawable, but no output or error are shown. Steps I'm doing:
1- Open PNG image in Sketch
2- Select the image from the left pane
3- Plugins -> Android Res Export -> Export Vector Drawable
4- Nothing happens, and no error shown

Also tried:
1- Open PNG image in Sketch
2- Select the image from the left pane
3- Plugins -> Android Res Export -> New Vector Drawable Asset
4- Select the folder created in the left pane, then
3- Plugins -> Android Res Export -> Export Vector Drawable
4- Nothing happens, and no error shown

This was tested on Sketch 41.2 (MAC)

**Comment by Ashung** [comment]
Bitmap layer can't export to vector drawable. Only shape layer can export to vector drawable. You need to know what's vector drawable. 

Read this [vector-asset-studio](https://developer.android.com/studio/write/vector-asset-studio.html), and this [VectorDrawable](https://developer.android.com/reference/android/graphics/drawable/VectorDrawable.html).
